name: null
task_name: "eval"
tags: []
split: test
run_all_splits: false
splits: [train, validation, test]
return_predictions: false
save_metrics: true
score_temperature: 1.0
score_bias: 0.0
ckpt_path: null
