name: null
task_name: "eval"
tags: []
split: test
run_all_splits: false
splits: [train, validation, test]
score_temperature: 1.0
ckpt_path: null
dataset_variants: null
require_dual_datasets: false
dataset_variant: null
