_target_: src.models.components.gflownet_rewards.System1GuidedReward

positive_threshold: 0.5
epsilon: 0.1
alpha_semantic: 0.1
base_success_reward: 1.0
terminal_bonus: 10.0
illegal_reward: 1.0e-8
length_penalty: 0.9
length_penalty_retriever: 0.95
semantic_success_threshold: 0.8
allow_semantic_only_success: false
require_full_path_hit: true
path_f1_power: 1.0
path_success_threshold: 0.8
