_target_: src.models.components.gflownet_state_encoder.GNNStateEncoder

hidden_dim: ${model.hidden_dim}
max_steps: ${model.env_cfg.max_steps}

num_layers: 2
dropout: 0.1

use_start_state: true
use_question_film: true
use_direction_emb: true
direction_vocab_size: 3

