defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 42
    n_trials: 10
    n_jobs: 1
    direction: minimize
    study_name: retriever_optuna
    params:
      model.model_cfg.dropout_p: choice(0.05, 0.1, 0.2)
      optimizer_cfg.lr: tag(log, interval(1e-4, 1e-3))
      optimizer_cfg.weight_decay: choice(0.0, 0.01)
