defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

optimized_metric: "val/reachability/answer_reachable@100"

hydra:
  sweeper:
    sampler:
      seed: 42
    n_trials: 10
    n_jobs: 1
    direction: maximize
    study_name: retriever_optuna
    params:
      model.retriever.dropout_p: choice(0.05, 0.1, 0.2)
      model.optimizer_cfg.lr: tag(log, interval(1e-4, 1e-3))
      model.optimizer_cfg.weight_decay: choice(0.0, 0.01)
