defaults:
  - base
  - _self_

model_cfg:
  model_type: evidential
  emb_dim: 1024
  kge_interaction: concat
  hidden_dim: 512
  lambda_prior_pos: 1.0
  lambda_prior_neg: 1.0

loss_cfg:
  clamp_min: 1.0e-6
