defaults:
  - base
  - _self_

model_cfg:
  model_type: hybrid
  emb_dim: 1024
  hidden_dim: 512
  kge_interaction: concat
  lambda_prior_pos: 1.0
  lambda_prior_neg: 1.0

loss_cfg:
  type: hybrid_vera
  temperature: 0.1
  rank_weight: 1.0
  cand_weight: 0.2
  query_weight: 0.5
  consistency_weight: 0.1
  alpha: 0.7
  beta: 1.0
  top_k: 1
  clamp_min: 1.0e-6
