# configs/dataset/cwq-sub.yaml

defaults:
  - base
  - _self_

name: cwq-sub
dataset_scope: sub
dataset_family: cwq
max_steps: 10
hf_dataset: rmanluo/RoG-cwq

sample_filter_paths:
  train: ${dataset.out_dir}/sub_filter.json
  validation: ${dataset.out_dir}/sub_filter.json
  test: ${dataset.out_dir}/sub_filter.json
