# configs/dataset/cwq-sub.yaml

name: cwq-sub
kb: freebase
dataset_scope: sub
dataset_family: cwq
max_steps: 10
hf_dataset: rmanluo/RoG-cwq

out_dir: ${paths.data_dir}/${dataset.dataset_family}/normalized
materialized_dir: ${paths.data_dir}/${dataset.dataset_family}/materialized
artifact_dir: ${paths.data_dir}/${dataset.dataset_family}/artifacts/${dataset.name}
distances_dir: ${dataset.materialized_dir}/distances

paths:
  vocabulary: ${dataset.materialized_dir}/vocabulary/vocabulary.lmdb
  embeddings: ${dataset.materialized_dir}/embeddings
  processed: ${dataset.materialized_dir}/processed

validate_on_get: false
cache_node_min_dists: true
cache_max_entries: 2048
sequential_sample_ids: true
preload_node_min_dists: true
sample_ids_source: lmdb
lmdb_readahead: true
distance_cache_format: pt
filter_missing_start:
  train: true
  validation: true
  test: true
filter_missing_answer:
  train: true
  validation: true
  test: true

sample_filter_paths:
  train: ${dataset.out_dir}/sub_filter.json
  validation: ${dataset.out_dir}/sub_filter.json
  test: ${dataset.out_dir}/sub_filter.json
nonzero_positive_filter_path: ${dataset.out_dir}/nonzero_positive_filter.json

entity_normalization: none
entity_text_mode: regex
text_prefixes: []
text_regex: "^(?!m\\.|g\\.).*"

column_map:
  question_id_field: id
  question_field: question
  answer_text_field: answer
  q_entity_field: q_entity
  a_entity_field: a_entity
  graph_field: graph
