# configs/dataset/cwq.yaml

defaults:
  - base
  - _self_

name: cwq
dataset_scope: full
dataset_family: cwq
max_steps: 10
hf_dataset: rmanluo/RoG-cwq

filter_missing_answer:
  train: false
  validation: false
  test: false
