# configs/dataset/cwq.yaml

name: cwq
kb: freebase

raw_root: ${paths.data_dir}/cwq/raw/data
out_dir: ${paths.data_dir}/cwq/normalized
materialized_dir: ${paths.data_dir}/cwq/materialized

paths:
  vocabulary: ${dataset.materialized_dir}/vocabulary/vocabulary.lmdb
  embeddings: ${dataset.materialized_dir}/embeddings
  processed: ${dataset.materialized_dir}/processed

entity_normalization: none
num_topics: 2
topic_pe:
  enabled: true
  precompute: true
  num_rounds: 2
  num_reverse_rounds: 2

column_map:
  question_id_field: id
  question_field: question
  answer_text_field: answer
  q_entity_field: q_entity
  a_entity_field: a_entity
  graph_field: graph
