name: gtsqa
kb: wikidata
raw_root: ${paths.data_dir}/GTSQA/raw/gtsqa-with-graphs
out_dir: ${paths.data_dir}/GTSQA/normalized
materialized_dir: ${paths.data_dir}/GTSQA/materialized
entity_normalization: none
num_topics: 2
topic_pe:
  enabled: true
  precompute: true
  num_rounds: 2
  num_reverse_rounds: 2
column_map:
  question_id_field: id
  question_field: question
  answer_text_field: all_answers_wikidata
  q_entity_field: seed_entities
  a_entity_field: answer_node
  graph_field: graph
  answer_subgraph_field: answer_subgraph
  graph_iso_field: graph_isomorphism
  redundant_field: redundant
  test_type_field: test_type
