# configs/dataset/webqsp.yaml

name: webqsp
kb: freebase

raw_root: ${paths.data_dir}/webqsp/raw/data
out_dir: ${paths.data_dir}/webqsp/normalized
materialized_dir: ${paths.data_dir}/webqsp/materialized

paths:
  vocabulary: ${dataset.materialized_dir}/vocabulary/vocabulary.lmdb
  embeddings: ${dataset.materialized_dir}/embeddings
  processed: ${dataset.materialized_dir}/processed

entity_normalization: none
undirected_traversal: false

column_map:
  question_id_field: id
  question_field: question
  answer_text_field: answer
  q_entity_field: q_entity
  a_entity_field: a_entity
  graph_field: graph
