# configs/dataset/webqsp.yaml

defaults:
  - base
  - _self_

name: webqsp
dataset_scope: full
dataset_family: webqsp
max_steps: 3
hf_dataset: rmanluo/RoG-webqsp

filter_missing_answer:
  train: false
  validation: false
  test: false
