# path to root directory (defaults to the directory where the entry script was launched)
root_dir: ${hydra:runtime.cwd}

# path to data directory (relative to project root by default)
data_dir: /mnt/data/retrieve

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
